### ISSUE TITLE
Plot changes/enhancements Epic

### ISSUE THREAD

**Issue by jrchudy** [informatics-isi-edu/deriva-webapps#142]
This Epic should be used to track each functionality of plot app that we still want to consider supporting after the migration to ReactJS. Some issues come from issue #73 and issue #122. Other comments are from individual issues.

Config Issues:
 - [ ] Config should be fetched from json file instead of the js (which is current implementation) (issue #73)
 - [ ] Config can be installed anywhere on the deployment (issue #92)
   - configs can be installed anywhere but the build process places them in the `config` folder
 - [ ] allow for default plot config using `*` as the key (issue #120)
 - [ ] add data to plotly object in config
   - treat data the same as layout and config
     - use as is and then add more values to it by the application to initialize defaults if not set
   - what if x/y arrays are part of data
     - if no queryPattern in traces then use x/y data
       - requires big changes to code to ignore making the requests and setting up the app without that data
     - if both x/y data and queryPattern in traces, then queryPattern data will be used ignoring the configuration in data
 - [ ] configuration changes in [comment](https://github.com/informatics-isi-edu/deriva-webapps/issues/135#issuecomment-1466661623) from issue #135
   - use consistent case, change all `snake_case` to `camelCase`
   - plot_type moved to each defined `trace` as `type`
     - allows for multiple traces to be defined with different plot types in one displayed plot
     - example: having a bar and line plot together
   - rename gene and study uri pattern properties to be generic.
     - part of "generalizing selector configuration language" to support more selectors than just gene/study on rbk/gudmap/atlas
 - [ ] change url_parameters to not mix the notion of url parameters and controller values
   - this will get tricky with how templates are defined. If url_parameters is a static object, that means templates should never rely on them and instead use `$filters` as defined below
     ```
     $url_parameters: {
       Study: ["xxxx", ...],
       NCBI_GeneID: "xxxx"
     },
     $filters: {
       Study: [Tuple, ...] // Study Tuples
       Gene: Tuple, // Gene Tuple
       rows: [Tuple, ...] // Replicate_Expression Tuple with all data
     },
     $row: [response.data[0], ...]
     ```
   
Layout and selector issues:
 - [ ] multiple pie charts displayed side by side. issue #126 describes this in more detail
 - [ ] Add a selector for data(dropdown) for a particular config. A single config can have multiple plots, those plots can have data from multiple sources - have a dropdown to select the source (issue #73)
   - should selector be per source, or all sources?
   - depends on if the data for chart 1 and 2 come from the same API but display different contents or display the same content visually different (bar and pie)
 - [ ] add a button to remove query params and enable all selectors
   - rough implementation done, revisit if needed
 - [ ] "_no studies selected_" italic text similar to "_all studies selected_"
 - [ ] truncate labels for x-axis display at "xx" characters
   - how to truncate and show tooltip in plotly?
   - index of terms that are truncated (similar to wikipedia "sources" section)
 - [ ] can legend be pushed above/below plot instead of trying to fit it "on top" of the plot 
   - plotly has a concept of xanchor and yanchor for the legend which allows for setting the legend position in relation to the plot
   - facebase asked for this for pie charts
   - new version of plotly app might handle this for us?
 - [ ] disable study selector instead of hide when study is in url parameters
 - [ ] open from iframe forces user to restart the changes they made to the selectors
   
Other plot changes:
 - [ ] Finalize logging in plot app (issue #115)
   - continuation of issue #109 
 - [ ] Further link support in plot app (issue #121)
   - hovertemplate_display_pattern
   - legend_markdown_pattern for `histogram` and `dot`
   - graphic_link_pattern for `dot`
 - [ ] if data is null, we use N/A
   - if data is empty string "", use Empty instead so the label isn't "missing"
 - [ ] help menu/link
   - where should this go?
   - in list of buttons that plotly has in upper right corner?
   - `/user-docs/plot-functionality.md` created
   
 - [ ] Just like other deriva web apps, the data should be fetched from the URL parameters. Need to support multiple plots from same URL. Currently that is happening via [config file](https://github.com/informatics-isi-edu/deriva-webapps/blob/config/plot-config.js) (issue #73)
   - May not be relevant anymore since we support multiple charts that make requests to very different `schema:table` paths
